apiVersion: apps/v1
kind: Deployment
metadata:
  name: classic-wcarefinance
  namespace: classic-sample-ns
  labels:
    app: classic-sample-application
    subname: wcarefinance
spec:
  selector:
    matchLabels:
      app: classic-sample-application
      subname: wcarefinance
  replicas: 1
  template:
    metadata:
      labels:
        app: classic-sample-application
        subname: wcarefinance
    spec:
      containers:
        - name: container-wcarefinance
          image: "gandhicloudlab/classic-wcarefinance:latest"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 9030